// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOQ_gr9NwqImQZ-HS9IGhMQGNwu_-jBqY',
    appId: '1:983671431796:android:c10404ff771244287ae721',
    messagingSenderId: '983671431796',
    projectId: 'vibzche-6ecc7',
    storageBucket: 'vibzche-6ecc7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVxmU8cU3sEY6X3fPPSe_kgWZyoJDqtvk',
    appId: '1:983671431796:web:1b419b17e755ef237ae721',
    messagingSenderId: '983671431796',
    projectId: 'vibzche-6ecc7',
    authDomain: 'vibzche-6ecc7.firebaseapp.com',
    storageBucket: 'vibzche-6ecc7.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2OIyF9PJZp4uWhcDt00Nh5-IzawvnsSk',
    appId: '1:983671431796:ios:042435fc44f06c8b7ae721',
    messagingSenderId: '983671431796',
    projectId: 'vibzche-6ecc7',
    storageBucket: 'vibzche-6ecc7.firebasestorage.app',
    iosBundleId: 'com.example.vibzcheck',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2OIyF9PJZp4uWhcDt00Nh5-IzawvnsSk',
    appId: '1:983671431796:ios:042435fc44f06c8b7ae721',
    messagingSenderId: '983671431796',
    projectId: 'vibzche-6ecc7',
    storageBucket: 'vibzche-6ecc7.firebasestorage.app',
    iosBundleId: 'com.example.vibzcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVxmU8cU3sEY6X3fPPSe_kgWZyoJDqtvk',
    appId: '1:983671431796:web:30ce4c4bb43246887ae721',
    messagingSenderId: '983671431796',
    projectId: 'vibzche-6ecc7',
    authDomain: 'vibzche-6ecc7.firebaseapp.com',
    storageBucket: 'vibzche-6ecc7.firebasestorage.app',
  );

}